# cloudbuild.yaml
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/repo-worker', '--cache-from', 'gcr.io/$PROJECT_ID/repo-worker', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/repo-worker']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'repo-worker'
  - '--image'
  - 'gcr.io/$PROJECT_ID/repo-worker'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '512M'
  - '--cpu'
  - '1'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '5m'

images:
- 'gcr.io/$PROJECT_ID/repo-worker'

timeout: '1200s'